function createarrow(figure1)
%CREATEARROW(figure1)
%  FIGURE1:  annotation figure

%  Auto-generated by MATLAB on 15-Feb-2023 14:59:52

% Create arrow
annotation(figure1,'arrow',[0.0696428571428571 0.289285714285714],...
    [0.389476190476191 0.623809523809524]);

